"""
CRM and logistics database models (SQLAlchemy ORM).

These models match the schema defined in ``sql/supabase_schema.sql`` and the
dynamic schema generated by ``supabase_schema.py``.
"""

import time

from sqlalchemy import (
    Boolean,
    Column,
    Float,
    ForeignKey,
    Integer,
    PrimaryKeyConstraint,
    String,
    Text,
)
from sqlalchemy.orm import declarative_base


Base = declarative_base()


class User(Base):
    """
    Kapruka agent user profile.

    This is the CRM profile for the person using the gift-concierge agent.
    Preference facts such as "user loves dark chocolate" or
    "user is allergic to nuts" should be stored in mem_facts,
    not directly inside this table.
    """

    __tablename__ = "users"

    user_id = Column(String, primary_key=True)
    external_user_id = Column(String, unique=True)
    full_name = Column(String)
    phone = Column(String)
    email = Column(String, unique=True)
    district = Column(String)
    province = Column(String)
    address = Column(Text)
    notes = Column(Text)
    active = Column(Boolean, nullable=False, default=True)
    created_at = Column(Integer, default=lambda: int(time.time()))
    updated_at = Column(
        Integer,
        default=lambda: int(time.time()),
        onupdate=lambda: int(time.time()),
    )

    def to_dict(self):
        """Convert the user profile to a dictionary."""
        return {
            "user_id": self.user_id,
            "external_user_id": self.external_user_id,
            "full_name": self.full_name,
            "phone": self.phone,
            "email": self.email,
            "district": self.district,
            "province": self.province,
            "address": self.address,
            "notes": self.notes,
            "active": self.active,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }


class DeliveryZone(Base):
    """Structured delivery coverage and capacity by district."""

    __tablename__ = "delivery_zones"

    district = Column(String, primary_key=True)
    delivery_available = Column(Boolean, nullable=False)
    same_day = Column(Boolean, nullable=False)
    express_available = Column(Boolean, nullable=False)
    minimum_notice_hours = Column(Integer, nullable=False)
    max_daily_orders = Column(Integer, nullable=False)
    active_couriers = Column(Integer, nullable=False)

    def to_dict(self):
        return {
            "district": self.district,
            "delivery_available": self.delivery_available,
            "same_day": self.same_day,
            "express_available": self.express_available,
            "minimum_notice_hours": self.minimum_notice_hours,
            "max_daily_orders": self.max_daily_orders,
            "active_couriers": self.active_couriers,
        }


class DeliverySlot(Base):
    """Structured delivery slot availability by district."""

    __tablename__ = "delivery_slots"
    __table_args__ = (
        PrimaryKeyConstraint("district", "slot", name="pk_delivery_slots"),
    )

    district = Column(
        String,
        ForeignKey("delivery_zones.district"),
        nullable=False,
    )
    slot = Column(String, nullable=False)
    capacity = Column(Integer, nullable=False)
    available = Column(Boolean, nullable=False)

    def to_dict(self):
        return {
            "district": self.district,
            "slot": self.slot,
            "capacity": self.capacity,
            "available": self.available,
        }


class CourierProfile(Base):
    """Courier capacity and availability by courier and district."""

    __tablename__ = "courier_profiles"

    courier_id = Column(String, primary_key=True)
    name = Column(String, nullable=False)
    district = Column(
        String,
        ForeignKey("delivery_zones.district"),
        nullable=False,
    )
    vehicle_type = Column(String, nullable=False)
    availability = Column(Boolean, nullable=False)
    max_deliveries_per_day = Column(Integer, nullable=False)
    rating = Column(Float, nullable=False)

    def to_dict(self):
        return {
            "courier_id": self.courier_id,
            "name": self.name,
            "district": self.district,
            "vehicle_type": self.vehicle_type,
            "availability": self.availability,
            "max_deliveries_per_day": self.max_deliveries_per_day,
            "rating": self.rating,
        }


class ProductDeliveryRule(Base):
    """Delivery constraints by product type."""

    __tablename__ = "product_delivery_rules"

    product_type = Column(String, primary_key=True)
    fragile = Column(Boolean, nullable=False)
    temperature_control_required = Column(Boolean, nullable=False)
    same_day_allowed = Column(Boolean, nullable=False)
    minimum_notice_hours = Column(Integer, nullable=False)
    max_delivery_distance_km = Column(Integer, nullable=False)

    def to_dict(self):
        return {
            "product_type": self.product_type,
            "fragile": self.fragile,
            "temperature_control_required": self.temperature_control_required,
            "same_day_allowed": self.same_day_allowed,
            "minimum_notice_hours": self.minimum_notice_hours,
            "max_delivery_distance_km": self.max_delivery_distance_km,
        }


class DeliveryHistory(Base):
    """Historical delivery outcomes used for logistics reasoning."""

    __tablename__ = "delivery_history"

    order_id = Column(String, primary_key=True)
    district = Column(
        String,
        ForeignKey("delivery_zones.district"),
        nullable=False,
    )
    product_type = Column(
        String,
        ForeignKey("product_delivery_rules.product_type"),
        nullable=False,
    )
    delivery_time_minutes = Column(Integer, nullable=False)
    status = Column(String, nullable=False)
    customer_rating = Column(Float, nullable=False)

    def to_dict(self):
        return {
            "order_id": self.order_id,
            "district": self.district,
            "product_type": self.product_type,
            "delivery_time_minutes": self.delivery_time_minutes,
            "status": self.status,
            "customer_rating": self.customer_rating,
        }
